### ISSUE TITLE
Server crashes if Skyroot Beds are disabled

### ISSUE THREAD

**Issue by Zachary2897** [raptor4694/aether-legacy-addon#3]
The server crashes unless the "Skyroot beds" and "Enable colored beds" config options are _both_ enabled. Disabling either of those two options (or disabling both of them) crashes the server.

I've tested this with Forge 14.23.5.2768 and with Forge 14.23.5.2854. In both cases, I used [The Aether v1.4.4](https://www.curseforge.com/minecraft/mc-mods/the-aether/files/2698950) and [Aether Continuation v1.2.3](https://www.curseforge.com/minecraft/mc-mods/aether-addon/files/2701616), with no other mods installed.

### Some crash reports

Forge 14.23.5.2768, "Skyroot beds" and "Enable colored beds" config options both disabled: [crash-2020-06-24_20.21.40-server.txt](https://github.com/raptor494/aether-legacy-addon/files/4828558/crash-2020-06-24_20.21.40-server.txt)
Forge 14.23.5.2768, "Skyroot beds" option enabled and "Enable colored beds" option disabled: [crash-2020-06-24_20.23.26-server.txt](https://github.com/raptor494/aether-legacy-addon/files/4828561/crash-2020-06-24_20.23.26-server.txt)
Forge 14.23.5.2768, "Skyroot beds" option disabled and "Enable colored beds" option enabled: [crash-2020-06-24_20.22.26-server.txt](https://github.com/raptor494/aether-legacy-addon/files/4828562/crash-2020-06-24_20.22.26-server.txt)

Forge 14.23.5.2854, "Skyroot beds" and "Enable colored beds" config options both disabled: [crash-2020-06-24_20.30.00-server.txt](https://github.com/raptor494/aether-legacy-addon/files/4828566/crash-2020-06-24_20.30.00-server.txt)
Forge 14.23.5.2854, "Skyroot beds" option enabled and "Enable colored beds" option disabled: [crash-2020-06-24_20.31.29-server.txt](https://github.com/raptor494/aether-legacy-addon/files/4828569/crash-2020-06-24_20.31.29-server.txt)
Forge 14.23.5.2854, "Skyroot beds" option disabled and "Enable colored beds" option enabled: [crash-2020-06-24_20.30.45-server.txt](https://github.com/raptor494/aether-legacy-addon/files/4828572/crash-2020-06-24_20.30.45-server.txt)

**Comment by raptor494** [comment]
Skyroot beds removed in the latest version of this mod, making this issue void
