### ISSUE TITLE
Incompatible with the latest Aether Legacy update

### ISSUE THREAD

**Issue by CalaMariGold** [raptor4694/aether-legacy-addon#5]
Incompatible with the latest Aether Legacy update. Any ETA for when this will be fixed?

**Comment by Zachary2897** [comment]
I've submitted a pull request (#6) which fixes compatibility between this mod and the new Aether update.

**Comment by raptor494** [comment]
Thanks, merged! Expect an official release soon, and I'll add you to the credits.

**Comment by CalaMariGold** [comment]
Any ETA when this will be uploaded to CurseForge?

**Comment by raptor494** [comment]
The file is processing now, sorry it took so long I have a lot on my plate
right now.
